# mage tab completion for fish
complete -c mage -f
complete -c mage -a '('/home/limavfabio/.local/share/mise/installs/go/1.26.4/bin/mage' -autocomplete 2>/dev/null)' -d 'mage target'
complete -c mage -s l -d 'list mage targets in this directory'
complete -c mage -s h -d 'show this help'
complete -c mage -s v -d 'show verbose output when running mage targets'
complete -c mage -s f -d 'force recreation of compiled magefile'
complete -c mage -l debug -d 'turn on debug messages'
complete -c mage -s t -r -d 'timeout in duration parsable format'
complete -c mage -s d -r -F -d 'directory to read magefiles from'
complete -c mage -s w -r -F -d 'working directory where magefiles will run'
complete -c mage -l keep -d 'keep intermediate mage files around after running'
complete -c mage -l compile -r -F -d 'output a static binary to the given path'
complete -c mage -l clean -d 'clean out old generated binaries from CACHE_DIR'
complete -c mage -l init -d 'create a starting template if no mage files exist'
complete -c mage -l version -d 'show version info for the mage binary'
complete -c mage -l gocmd -r -d 'use the given go binary to compile the output'
complete -c mage -l goos -r -d 'set GOOS for binary produced with -compile'
complete -c mage -l goarch -r -d 'set GOARCH for binary produced with -compile'
complete -c mage -l ldflags -r -d 'set ldflags for binary produced with -compile'
complete -c mage -l autocomplete -d 'print target names for shell completion'
complete -c mage -l install -r -a 'bash zsh fish powershell pwsh' -d 'install shell completion'
complete -c mage -l multiline -d 'retain line returns in help text'
